title: ISE
description: Industrial Software Engineering partnership site at IT University of Copenhagen, connecting industry professionals with academic projects and fostering collaborative software development initiatives.
repository: ind-sw-eng/ise
url: https://ind-sw-eng.github.io
baseurl: "/ise"

plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tailwindcss

include: ["_pages"]

collections:
  projects:
    output: true
    permalink: /projects/:path/
